# Generated by Django 4.2 on 2026-05-09 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brew_type', models.CharField(choices=[('beer', 'Beer'), ('mead', 'Mead'), ('cider', 'Cider'), ('other', 'Other')], default='beer', max_length=20)),
                ('style', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('fermenting', 'Fermenting'), ('conditioning', 'Conditioning'), ('ready', 'Ready'), ('archived', 'Archived')], default='fermenting', max_length=20)),
                ('brew_date', models.DateField()),
                ('original_gravity', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('final_gravity', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='brews.recipe')),
            ],
        ),
    ]
