# Generated by Django 4.2 on 2026-07-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='targer_final_gravity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='target_gravity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
