# Generated by Django 4.2 on 2026-07-17 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brews', '0002_recipe_targer_final_gravity_recipe_target_gravity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='targer_final_gravity',
            new_name='target_final_gravity',
        ),
    ]
